service:
  name: news-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

environment:
  AuthKey: "ae1e74aa9f4e5c94203f8ec2f27f6ed2"


functions:
  searchGNews:
    handler: handler.searchNews
    events:
      - http:
          method: get
          path: search/:q

  searchGTopics:
    handler: handler.searchTopic
    events:
      - http:
          method: get
          path: topic/:topic
